[network]
    node =  "北游12"
    cron = "*/10 * * * * *" #每10秒进行一次定时任务
    api  = "https://m.laiu8.cn/intelligentapi/todayflightsdata" 
    [network.pingtest]
        enabled = true
        pinginterval = 1 
        [[network.pingtest.device]]
            name  = "route-1"
            ip = "10.26.40.52"
        [[network.pingtest.device]]
            name  = "route-2"
            ip = "10.26.40.56"
    [network.bindwidthtest]
        enabled = true
        bindwidthdurtion = 20s
        [[network.bindwidthtest.device]]
            name  = "route-1"
            ip = "10.26.40.52" 
        [[network.bindwidthtest.device]]
            name  = "route-1"
            ip = "10.26.40.56" 
        
[mail]
  host = "smtp.163.com"
  pass = "GNTPENWQNFHPQWGS"
  port = 465
  to = "260431910@qq.com"
  user = "baird0917@163.com"

[data]
    pingfile = "./data/pingtest"

