[network]
    node =  "北游16"
    cron = "*/60 * * * * *" #每10秒进行一次定时任务
    [network.pingtest]
        enabled = true
        pinginterval = 1 
        [[network.pingtest.device]]
            name  = "route-1"
            ip = "192.168.1.1"
        [[network.pingtest.device]]
            name  = "route-2"
            ip = "192.168.1.1"
    [network.bindwidthtest]
        enabled = true
        [[network.bindwidthtest.device]]
            name  = "route-1"
            ip = "192.168.1.100" 
        [[network.bindwidthtest.device]]
            name  = "route-1"
            ip = "192.168.1.102" 
        
[mail]
  host = "smtp.163.com"
  pass = "GNTPENWQNFHPQWGS"
  port = 465
  to = "260431910@qq.com"
  user = "baird0917@163.com"

[data]
    pingfile = "./data/pingtest"

